"""Behavioral cloning and DAgger for the discrete GridWorld.

The expert is an exact policy computed by dynamic programming.  This makes the
imitation experiment self-contained: every state can be labelled without a
pretrained checkpoint or a hidden external oracle.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import torch
from torch import nn

from edu_rl.core.networks import CategoricalActor


@dataclass
class ImitationResult:
    policy: CategoricalActor
    losses: list[float]
    evaluation_returns: list[float]
    dataset_sizes: list[int]


def one_hot_states(states: np.ndarray | list[int], n_states: int) -> torch.Tensor:
    states_tensor = torch.as_tensor(states, dtype=torch.long)
    return torch.nn.functional.one_hot(states_tensor, n_states).float()


def collect_expert_dataset(
    env: object,
    expert_policy: np.ndarray,
    *,
    episodes: int,
    seed: int,
) -> tuple[list[int], list[int]]:
    """Collect state/action pairs from trajectories generated by the expert."""

    states: list[int] = []
    actions: list[int] = []
    for episode in range(episodes):
        state, _ = env.reset(seed=seed + episode)
        done = False
        while not done:
            action = int(expert_policy[state])
            states.append(int(state))
            actions.append(action)
            state, _, terminated, truncated, _ = env.step(action)
            done = terminated or truncated
    return states, actions


def fit_behavioral_cloning(
    states: list[int],
    actions: list[int],
    *,
    n_states: int,
    n_actions: int,
    policy: CategoricalActor | None = None,
    epochs: int = 100,
    learning_rate: float = 3e-3,
    seed: int = 0,
) -> tuple[CategoricalActor, list[float]]:
    """Fit the expert labels by maximum likelihood (cross-entropy)."""

    torch.manual_seed(seed)
    if policy is None:
        policy = CategoricalActor(n_states, n_actions, (32,))
    optimizer = torch.optim.Adam(policy.parameters(), lr=learning_rate)
    observations = one_hot_states(states, n_states)
    labels = torch.as_tensor(actions, dtype=torch.long)
    losses: list[float] = []

    for _ in range(epochs):
        logits = policy.logits_network(observations)
        loss = nn.functional.cross_entropy(logits, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        losses.append(float(loss.detach()))
    return policy, losses


@torch.no_grad()
def evaluate_grid_policy(
    env: object,
    policy: CategoricalActor,
    *,
    episodes: int = 50,
    seed: int = 1_000,
) -> float:
    returns: list[float] = []
    for episode in range(episodes):
        state, _ = env.reset(seed=seed + episode)
        done = False
        episode_return = 0.0
        while not done:
            observation = one_hot_states([state], env.n_states)
            action = int(policy.deterministic(observation).item())
            state, reward, terminated, truncated, _ = env.step(action)
            episode_return += float(reward)
            done = terminated or truncated
        returns.append(episode_return)
    return float(np.mean(returns))


def behavioral_cloning(
    env: object,
    expert_policy: np.ndarray,
    *,
    expert_episodes: int = 20,
    epochs: int = 200,
    seed: int = 0,
) -> ImitationResult:
    """Train only on the state distribution visited by the expert."""

    states, actions = collect_expert_dataset(
        env, expert_policy, episodes=expert_episodes, seed=seed
    )
    policy, losses = fit_behavioral_cloning(
        states,
        actions,
        n_states=env.n_states,
        n_actions=env.n_actions,
        epochs=epochs,
        seed=seed,
    )
    evaluation_return = evaluate_grid_policy(env, policy)
    return ImitationResult(
        policy=policy,
        losses=losses,
        evaluation_returns=[evaluation_return],
        dataset_sizes=[len(states)],
    )


def dagger(
    env: object,
    expert_policy: np.ndarray,
    *,
    initial_expert_episodes: int = 5,
    iterations: int = 8,
    learner_episodes_per_iteration: int = 10,
    epochs_per_iteration: int = 50,
    seed: int = 0,
) -> ImitationResult:
    """Aggregate expert labels on states induced by the current learner.

    DAgger does not ask the expert to control the environment after the initial
    dataset.  It asks what action the expert *would have taken* at every state
    visited by the learner, which directly targets covariate shift.
    """

    states, actions = collect_expert_dataset(
        env, expert_policy, episodes=initial_expert_episodes, seed=seed
    )
    policy: CategoricalActor | None = None
    all_losses: list[float] = []
    evaluation_returns: list[float] = []
    dataset_sizes: list[int] = []

    for iteration in range(iterations):
        policy, losses = fit_behavioral_cloning(
            states,
            actions,
            n_states=env.n_states,
            n_actions=env.n_actions,
            policy=policy,
            epochs=epochs_per_iteration,
            seed=seed + iteration,
        )
        all_losses.extend(losses)
        evaluation_returns.append(evaluate_grid_policy(env, policy))
        dataset_sizes.append(len(states))

        # Roll out the learner but label every visited state with the oracle.
        for episode in range(learner_episodes_per_iteration):
            state, _ = env.reset(seed=seed + 10_000 + iteration * 100 + episode)
            done = False
            while not done:
                observation = one_hot_states([state], env.n_states)
                learner_action = int(policy.deterministic(observation).item())
                states.append(int(state))
                actions.append(int(expert_policy[state]))
                state, _, terminated, truncated, _ = env.step(learner_action)
                done = terminated or truncated

    assert policy is not None
    return ImitationResult(
        policy=policy,
        losses=all_losses,
        evaluation_returns=evaluation_returns,
        dataset_sizes=dataset_sizes,
    )

